### ISSUE TITLE
rollup-plugin-ractive-bin can not be found

### ISSUE THREAD

**Issue by ceremcem** [evs-chris/raui#1]
While following the install procedure, `npm install` gives the following: 

```
ceremcem@cca-erik:ractive-materialish$ npm install
npm ERR! code E404
npm ERR! 404 Not Found: rollup-plugin-ractive-bin@^1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ceremcem/.npm/_logs/2017-11-03T03_39_59_270Z-debug.log
```
(full debug log is [here](https://gist.github.com/b631e7be54dd1955fb5c8c23ad10e1ef))

**Comment by evs-chris** [comment]
I suppose it _would_ help to publish the rollup plugin... :grinning:

Should be good now.

**Comment by ceremcem** [comment]
Yes, it installs now.
